<a href="https://colab.research.google.com/github/ronniesong0809/Dive-into-Deep-Learning/blob/master/chapter4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
%matplotlib inline
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow import initializers as init
print(tf.__version__)

2.2.0


In [17]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.2.0


In [18]:
class MLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = tf.keras.layers.Flatten()
        self.dense1 = tf.keras.layers.Dense(units=256, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(units=10)

    def call(self, inputs):         
        x = self.flatten(inputs)   
        x = self.dense1(x)    
        output = self.dense2(x)     
        return output

In [19]:
X = tf.random.uniform((2,20))
net = MLP()
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.13726619,  0.03564936,  0.19467469,  0.33304805,  0.1590392 ,
         0.43265438, -0.07955971, -0.00868493, -0.12551825,  0.2769177 ],
       [ 0.11571886,  0.09873   ,  0.01119184,  0.27985704,  0.07780931,
         0.4602334 ,  0.01183741, -0.07340824, -0.06841019,  0.23511659]],
      dtype=float32)>

In [20]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation=tf.nn.relu),
    tf.keras.layers.Dense(10),
])

model(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.50330675, -0.20456609, -0.22456723, -0.16486989,  0.06633512,
        -0.06032762, -0.23902464,  0.07759501,  0.02197033, -0.14143237],
       [ 0.12093291, -0.23195106, -0.570036  ,  0.2271543 ,  0.04984084,
        -0.05008057, -0.16191682,  0.01433781, -0.17586872, -0.173768  ]],
      dtype=float32)>

In [21]:
class FancyMLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = tf.keras.layers.Flatten()
        self.rand_weight = tf.constant(
            tf.random.uniform((20,20)))
        self.dense = tf.keras.layers.Dense(units=20, activation=tf.nn.relu)

    def call(self, inputs):         
        x = self.flatten(inputs)   
        x = tf.nn.relu(tf.matmul(x, self.rand_weight) + 1)
        x = self.dense(x)    
        while tf.norm(x) > 1:
            x /= 2
        if tf.norm(x) < 0.8:
            x *= 10
        return tf.reduce_sum(x)

In [22]:
net = FancyMLP()
net(X)

<tf.Tensor: shape=(), dtype=float32, numpy=21.63995>

In [23]:
class NestMLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.net = tf.keras.Sequential()
        self.net.add(tf.keras.layers.Flatten())
        self.net.add(tf.keras.layers.Dense(64, activation=tf.nn.relu))
        self.net.add(tf.keras.layers.Dense(32, activation=tf.nn.relu))
        self.dense = tf.keras.layers.Dense(units=16, activation=tf.nn.relu)


    def call(self, inputs):         
        return self.dense(self.net(inputs))

net = tf.keras.Sequential()
net.add(NestMLP())
net.add(tf.keras.layers.Dense(20))
net.add(FancyMLP())

net(X)

<tf.Tensor: shape=(), dtype=float32, numpy=3.2830195>